### ISSUE TITLE
[feat] redis 관련 추가 작업 

### ISSUE THREAD

**Issue by chaewonni** [OMZigak/KKUMER#33]
## Issue 📌
[//]: # (전체 작업에 대해 간략한 설명)
- redis 관련 추가 작업 (redisConfig 등)

## Todo ✔️
[//]: # (해야할 일 간단한 체크리스트)
- [ ] N/A

**Comment by tkdwns414** [comment]
https://github.com/OMZigak/KKUMER/pull/34#issuecomment-2365259582 내용으로 close 되었습니다!

**Comment by tkdwns414** [comment]
https://github.com/OMZigak/KKUMER/pull/34#issuecomment-2365259582 내용으로 close 되었습니다!
